import gradio as gr
import google.generativeai as genai
from pypdf import PdfReader
import os
import markdown
from xhtml2pdf import pisa

# --- CONFIGURATION ---
api_key = os.environ.get("GEMINI_API_KEY")
if not api_key:
    # Fallback for local testing if env var is missing
    print("⚠️ Warning: GEMINI_API_KEY not found. App may crash.")

genai.configure(api_key=api_key)
model = genai.GenerativeModel("gemini-2.0-flash")

# --- PDF GENERATOR ENGINE ---
def create_pdf(markdown_content):
    """Converts Markdown to a Professional PDF"""
    
    # 1. Convert Markdown to HTML
    html_content = markdown.markdown(markdown_content)
    
    # 2. Wrap in a Corporate HTML Template with CSS
    styled_html = f"""
    <html>
    <head>
        <style>
            @page {{
                size: A4;
                margin: 2cm;
            }}
            body {{
                font-family: Helvetica, Arial, sans-serif;
                font-size: 11pt;
                line-height: 1.6;
                color: #333333;
            }}
            h1 {{
                color: #2c3e50;
                font-size: 18pt;
                border-bottom: 2px solid #2c3e50;
                padding-bottom: 10px;
                margin-top: 0px;
            }}
            h2 {{
                color: #16a085;
                font-size: 14pt;
                margin-top: 25px;
                margin-bottom: 10px;
            }}
            h3 {{
                color: #2980b9;
                font-size: 12pt;
                margin-top: 20px;
            }}
            ul {{
                margin-bottom: 15px;
            }}
            li {{
                margin-bottom: 5px;
            }}
            strong {{
                color: #000000;
            }}
            .footer {{
                position: fixed;
                bottom: 0;
                width: 100%;
                text-align: center;
                font-size: 9pt;
                color: #7f8c8d;
                border-top: 1px solid #bdc3c7;
                padding-top: 10px;
            }}
        </style>
    </head>
    <body>
        <h1>Executive Career Strategy</h1>
        {html_content}
        <div class='footer'>
            Generated by AI Executive Career Architect • Confidential Strategy Report
        </div>
    </body>
    </html>
    """
    
    # 3. Write to PDF file
    output_filename = "Executive_Strategy_Report.pdf"
    with open(output_filename, "wb") as f:
        pisa.CreatePDF(styled_html, dest=f)
    
    return output_filename

# --- CORE LOGIC ---
def extract_pdf_text(filepath):
    if not filepath: return ""
    try:
        reader = PdfReader(filepath)
        text = ""
        for page in reader.pages:
            text += page.extract_text() + "\n"
        return text
    except Exception as e:
        return f"Error reading file: {e}"

def career_coach_logic(resume_file, jd_file):
    if not resume_file or not jd_file:
        return "⚠️ Please upload BOTH files to start.", None

    # Read files
    res_text = extract_pdf_text(resume_file)
    jd_text = extract_pdf_text(jd_file)

    # Executive Prompt
    prompt = f"""
    # Executive Strategy Prompt (System-Level) — BLUF Reporting Enabled

    ROLE: Executive Career Strategist (C-suite/VP/Director caliber).

    INPUTS:
    1) RESUME: {res_text}
    2) JOB DESCRIPTION: {jd_text}

    OBJECTIVE:
    Assess executive-level fit and produce a BLUF-first report.

    OUTPUT FORMAT (STRICT MARKDOWN):

    # 🏁 BLUF: The Verdict
    - **Status:** [STRONG MATCH | POSSIBLE MATCH | WEAK MATCH]
    - **Score:** [0–100]
    - **One-line verdict:** (Summary)

    ---
    # 🚩 Critical Gaps
    - **Gap 1:** (What is missing)
    - **Gap 2:** (What is missing)

    ---
    # ✍️ Executive Resume Rewrite
    (Rewrite the top 2 roles using CAR format - Context, Action, Result. Use bolding for metrics.)

    ---
    # ✉️ The Hook
    (3-sentence executive email opener)
    """
    
    try:
        # 1. Generate Text
        response = model.generate_content(prompt)
        ai_text = response.text
        
        # 2. Generate PDF
        pdf_path = create_pdf(ai_text)
        
        return ai_text, pdf_path
        
    except Exception as e:
        return f"AI Error: {e}", None

# --- THE UI ---
with gr.Blocks(theme=gr.themes.Soft(primary_hue="slate")) as app:
    gr.Markdown("# 🏛️ Executive Career Architect")
    gr.Markdown("Exclusive Access. Upload your documents to generate a Boardroom-Ready Strategy.")
    
    with gr.Row():
        res_upload = gr.File(label="1. Executive Resume (PDF)", file_types=[".pdf"])
        jd_upload = gr.File(label="2. Target Job Description (PDF)", file_types=[".pdf"])
    
    btn = gr.Button("Generate Strategy & Report", variant="primary", size="lg")
    
    # Outputs: One for screen, one for download
    with gr.Row():
        output_box = gr.Markdown(label="Strategic Analysis")
        pdf_download = gr.File(label="Download Official Report (PDF)")
    
    btn.click(fn=career_coach_logic, inputs=[res_upload, jd_upload], outputs=[output_box, pdf_download])

# Launch
PORT = int(os.environ.get("PORT", 7860))
app.launch(server_name="0.0.0.0", server_port=PORT, auth=("vip_user", "career2026"))
