import gradio as gr
import google.generativeai as genai
from pypdf import PdfReader
import os
import markdown
from xhtml2pdf import pisa
import requests

# --- 1. CONFIGURATION ---
api_key = os.environ.get("GEMINI_API_KEY")
if not api_key:
    print("⚠️ SYSTEM ALERT: GEMINI_API_KEY is missing in Render Environment Variables.")

genai.configure(api_key=api_key)
model = genai.GenerativeModel("gemini-2.0-flash")

# CRITICAL: Your Exact Product ID (Do not change this)
GUMROAD_PRODUCT_ID = "A70XLqybP3M3f6C-euPZzg=="

# --- 2. AUTHENTICATION (BUSINESS LOGIC) ---
def verify_gumroad_key(license_key):
    license_key = str(license_key).strip()
    
    if not license_key:
        return False, "⚠️ Please enter your License Key."

    print(f"🔒 Verifying Key against ID: {GUMROAD_PRODUCT_ID}...")

    try:
        response = requests.post(
            "https://api.gumroad.com/v2/licenses/verify",
            data={
                "product_id": GUMROAD_PRODUCT_ID, 
                "license_key": license_key
            },
            timeout=10
        )
        
        data = response.json()
        
        if data.get("success") == True:
            if data["purchase"].get("refunded", False):
                return False, "❌ Access Denied: This purchase has been refunded."
            if data["purchase"].get("chargebacked", False):
                return False, "❌ Access Denied: Payment dispute detected."
            
            return True, "✅ Verified. Welcome to AI Career Architect."
        else:
            return False, "❌ Invalid Key. Please check the License Key sent to your email."
            
    except Exception as e:
        print(f"Connection Error: {e}")
        return False, "⚠️ Connection Error. Please try again."

# --- 3. REPORT GENERATOR (PDF) ---
def create_pdf(markdown_content):
    html_body = markdown.markdown(markdown_content)
    
    # Professional Styling for Executive Reports
    styled_html = f"""
    <html>
    <head>
        <style>
            @page {{ size: A4; margin: 2.5cm; }}
            body {{ font-family: Helvetica, sans-serif; font-size: 11pt; line-height: 1.5; color: #333; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #2c3e50; padding-bottom: 10px; margin-top: 0; }}
            h2 {{ color: #2980b9; margin-top: 25px; font-size: 14pt; border-bottom: 1px solid #eee; }}
            h3 {{ color: #7f8c8d; font-size: 12pt; text-transform: uppercase; margin-top: 20px; }}
            strong {{ color: #000; font-weight: bold; }}
            li {{ margin-bottom: 5px; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background-color: #f2f2f2; color: #333; }}
            .footer {{ position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 9pt; color: #aaa; border-top: 1px solid #ddd; padding-top: 10px; }}
        </style>
    </head>
    <body>
        <h1>Executive Career Strategy Report</h1>
        {html_body}
        <div class='footer'>Confidential • Generated by AI Career Architect • Jicu Limited</div>
    </body>
    </html>
    """
    
    output_filename = "Executive_Strategy_Report.pdf"
    with open(output_filename, "wb") as f:
        pisa.CreatePDF(styled_html, dest=f)
    return output_filename

# --- 4. AI CORE INTELLIGENCE (THE UPGRADE) ---
def extract_pdf_text(filepath):
    if not filepath: return ""
    try:
        reader = PdfReader(filepath)
        text = ""
        for page in reader.pages: text += page.extract_text() + "\n"
        return text
    except Exception as e: return f"Error reading PDF: {str(e)}"

def career_coach_logic(license_key, resume_file, jd_file):
    # 1. Security Check
    is_valid, msg = verify_gumroad_key(license_key)
    if not is_valid:
        return f"🔒 SECURITY ALERT: {msg}", None

    # 2. File Check
    if not resume_file or not jd_file:
        return "⚠️ Missing Files: Please upload BOTH your Resume and the Job Description.", None

    # 3. Processing
    res_text = extract_pdf_text(resume_file)
    jd_text = extract_pdf_text(jd_file)

    # --- THE UPDATED "HIGH GRADE" PROMPT ---
    prompt = f"""
    ROLE: You are an elite Executive Career Strategist.
    TASK: Perform a ruthless gap analysis and then completely REWRITE the candidate's profile to match the target role.
    
    INPUTS: 
    - CANDIDATE RESUME: {res_text} 
    - TARGET JOB DESCRIPTION (JD): {jd_text}
    
    GUIDELINES:
    - Tone: Executive, authoritative, and metric-driven.
    - Format: Strict Markdown.
    - Constraint: Do not invent facts. If a metric is missing, focus on the scope/responsibility.
    
    OUTPUT STRUCTURE:
    
    # 🏁 PART 1: STRATEGIC FIT ANALYSIS
    ## 🚦 The Verdict
    * **Status:** [STRONG MATCH / POSSIBLE / WEAK]
    * **Fit Score:** [0-100]
    * **Executive Summary:** (2 sentences. Be direct. e.g., "Candidate is a strong technical match but lacks the specific 'Local Content' experience required in Brazil.")
    
    ## 🚩 Critical Gaps & Risks
    * (Identify 3 specific skills or experiences found in the JD that are weak or missing in the Resume)
    
    ---
    
    # ✍️ PART 2: THE EXECUTIVE REWRITE
    *(Instruction: Rewrite the top 1/3rd of the resume to perfectly align with the JD)*
    
    ## 👤 Proposed Headline
    *(Create a new, specific Job Title for the resume that matches the JD. e.g., "Senior Projects & Field Operations Lead")*
    
    ## 💎 Professional Summary (Optimized)
    *(Rewrite the bio. Front-load the JD's keywords. Mention years of experience, specific industries, and key achievements immediately. 4-5 lines max.)*
    
    ## 🛠️ Core Competencies (ATS Grid)
    *(Create a 3x3 table of the TOP hard skills found in the JD that the candidate possesses)*
    | Category 1 | Category 2 | Category 3 |
    | :--- | :--- | :--- |
    | (Skill) | (Skill) | (Skill) |
    | (Skill) | (Skill) | (Skill) |
    
    ## 🚀 Experience (Top 2 Roles Rewritten)
    *(Rewrite the 2 most recent or relevant roles. Use the 'Context-Action-Result' format. Bold the metrics.)*
    
    **[Role Title]** | *[Company]* | *[Dates]*
    * **[Key Outcome/Metric]:** [Description of action]. (e.g., "Led cost optimization drive saving **$4M USD** by...")
    * **[JD Keyword]:** [Description of action].
    * **[Leadership/Scope]:** [Description of action].
    
    ---
    
    # ✉️ PART 3: OUTREACH STRATEGY
    ## 🎯 The "Hook" (Email Opener)
    *(Write a 3-sentence opening paragraph for a cover letter or LinkedIn DM. Address the Hiring Manager. Acknowledge the specific pain points in the JD and how the candidate solves them immediately.)*
    """
    
    try:
        response = model.generate_content(prompt)
        ai_text = response.text
        pdf_path = create_pdf(ai_text)
        return ai_text, pdf_path
    except Exception as e:
        return f"System Error: {e}", None

# --- 5. UI CONSTRUCTION ---
LOGO_PATH = "logo.jpg" 

LEGAL_TEXT = """
### Privacy Policy & Legal Disclaimer
**Effective Date:** January 2026 | **Seller:** Jicu Limited

**1. Data Privacy**
* **We do not store your files.** Uploaded documents are processed in-memory by secure AI and discarded immediately after generation.
* **We do not sell data.** Your personal information is never sold to third parties.

**2. Legal Disclaimer**
* **No Guarantee of Employment:** This tool is for optimization purposes only. Use of this service does not guarantee job interviews or offers.
* **AI Limitations:** Artificial intelligence can make errors. You are solely responsible for verifying all facts, dates, and metrics in your rewritten resume before submitting it.
"""

with gr.Blocks(theme=gr.themes.Soft(primary_hue="slate")) as app:
    
    user_key_state = gr.State("")

    # === VIEW 1: LOGIN SCREEN ===
    with gr.Column(visible=True) as login_view:
        gr.Markdown("## ") # Spacer
        with gr.Row():
            with gr.Column(scale=1): pass
            with gr.Column(scale=2):
                
                if os.path.exists(LOGO_PATH):
                    gr.Image(value=LOGO_PATH, show_label=False, height=180, container=False)
                else:
                    gr.Markdown("## 🏛️ AI Career Architect")

                gr.Markdown("# 🔒 Client Portal")
                gr.Markdown("Please enter your **Gumroad License Key** to access the strategist.")
                
                key_input = gr.Textbox(
                    label="License Key", 
                    placeholder="e.g. 14BCC8C0-...", 
                    type="password"
                )
                login_btn = gr.Button("Unlock Access", variant="primary", size="lg")
                login_msg = gr.Markdown("")
            with gr.Column(scale=1): pass

    # === VIEW 2: MAIN APPLICATION ===
    with gr.Column(visible=False) as main_view:
        
        with gr.Row():
            if os.path.exists(LOGO_PATH):
                gr.Image(value=LOGO_PATH, show_label=False, height=60, scale=0, container=False)
            gr.Markdown("# 🏛️ AI Career Architect")
        
        with gr.Tabs():
            
            # TAB 1: STRATEGY TOOL
            with gr.TabItem("🚀 Career Strategist"):
                gr.Markdown("### Upload your documents to generate a ruthless gap analysis and executive rewrite.")
                with gr.Row():
                    res_upload = gr.File(label="📂 1. Upload Resume (PDF)", file_types=[".pdf"])
                    jd_upload = gr.File(label="🎯 2. Upload Target Job Description (PDF)", file_types=[".pdf"])
                
                generate_btn = gr.Button("✨ Generate Executive Strategy", variant="primary", size="lg")
                
                with gr.Row():
                    output_box = gr.Markdown(label="Strategic Analysis")
                    pdf_download = gr.File(label="📄 Download Official PDF Report")

            # TAB 2: LEGAL & PRIVACY
            with gr.TabItem("⚖️ Legal & Privacy"):
                gr.Markdown(LEGAL_TEXT)

    # === EVENT WIRING ===
    def attempt_login(key):
        is_valid, msg = verify_gumroad_key(key)
        if is_valid:
            return {
                login_view: gr.update(visible=False),
                main_view: gr.update(visible=True),
                user_key_state: key,
                login_msg: ""
            }
        else:
            return {
                login_view: gr.update(visible=True),
                main_view: gr.update(visible=False),
                user_key_state: "",
                login_msg: f"⚠️ {msg}"
            }

    login_btn.click(attempt_login, inputs=[key_input], outputs=[login_view, main_view, user_key_state, login_msg])
    generate_btn.click(career_coach_logic, inputs=[user_key_state, res_upload, jd_upload], outputs=[output_box, pdf_download])

# --- LAUNCH SERVER ---
PORT = int(os.environ.get("PORT", 7860))
app.launch(server_name="0.0.0.0", server_port=PORT)
